# Generated by Django 5.1.6 on 2025-02-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OvercurrentRelay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('relay_setting_current', models.FloatField()),
                ('time_multiplier_setting', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kva_rating', models.IntegerField()),
                ('primary_voltage', models.FloatField()),
                ('secondary_voltage', models.FloatField()),
                ('impedance', models.FloatField()),
            ],
        ),
    ]
