# Generated by Django 5.1.6 on 2025-02-25 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_rename_overcurrentrelay_relay'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='type',
            field=models.CharField(choices=[('oc', 'Overcurrent'), ('dist', 'Distance')], default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
    ]
