# Generated by Django 5.1.6 on 2025-02-25 22:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0003_relay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay',
            name='protected_equipment',
            field=models.CharField(choices=[('tra', 'Transformer'), ('line', 'Transmission Line')], default=django.utils.timezone.now, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relay',
            name='type',
            field=models.CharField(choices=[('oc', 'Overcurrent'), ('dist', 'Distance'), ('diff', 'Differential')], max_length=4),
        ),
    ]
