# Generated by Django 5.1.6 on 2025-02-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0005_remove_relay_relay_setting_current_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransmissionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('kva_rating', models.IntegerField()),
                ('voltage_rating', models.FloatField()),
                ('impedance', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='relay',
            name='current_setting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relay',
            name='curve_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='relay',
            name='standard',
            field=models.CharField(blank=True, choices=[('iec', 'IEC'), ('ieee', 'IEEE')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='relay',
            name='tds',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relay',
            name='type',
            field=models.CharField(choices=[('oc', 'Overcurrent'), ('dist', 'Distance'), ('diff', 'Differential'), ('ref', 'Restricted Earth Fault')], max_length=4),
        ),
    ]
