# Generated by Django 5.1.6 on 2025-02-27 07:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0007_transformer_phase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmissionline',
            name='length',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transmissionline',
            name='phase_type',
            field=models.CharField(choices=[('single', 'Single-Phase'), ('three', 'Three-Phase')], default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
