# Generated by Django 5.1.6 on 2025-02-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0008_transmissionline_length_transmissionline_phase_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transmissionline',
            name='r_per_km',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transmissionline',
            name='x_per_km',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transmissionline',
            name='phase_type',
            field=models.CharField(choices=[('single', 'Single-Phase'), ('three', 'Three-Phase')], default='three', max_length=6),
        ),
    ]
