# Generated by Django 5.1.6 on 2025-03-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('oc', 'Overcurrent'), ('dist', 'Distance'), ('diff', 'Differential'), ('ref', 'Restricted Earth Fault')], max_length=4)),
                ('protected_equipment', models.CharField(choices=[('tra', 'Transformer'), ('line', 'Transmission Line')], max_length=4)),
                ('standard', models.CharField(blank=True, choices=[('iec', 'IEC'), ('ieee', 'IEEE')], max_length=4, null=True)),
                ('curve_type', models.CharField(blank=True, max_length=20, null=True)),
                ('tds', models.FloatField(blank=True, null=True)),
                ('current_setting', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
